# Generated by Django 4.2.2 on 2023-07-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shade_color',
            name='hex',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shade_color',
            name='rgb',
            field=models.CharField(max_length=20),
        ),
    ]
