# Generated by Django 4.2.2 on 2023-07-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_shade_color_hex_alter_shade_color_rgb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shade_color',
            name='base_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shades', to='main_app.base_color'),
        ),
    ]
